extrasens/extrasens/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('extratest.urls', namespace='extratest')),
    path('admin/', admin.site.urls),
]

extrasens/extratest/urls.py
from django.urls import path
from . import views

app_name = 'extratest'

urlpatterns = [
    path('', views.index, name='index'),
    path('examples/', views.examples, name='examples'),
    path('input_number/', views.input_number, name='input_number'),
    path('results/', views.results, name='results'),
] 

extrasens/extratest/models.py
from django.conf import settings
from django.contrib.sessions.models import Session
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from random import randint


#class SessionMiddleware (models.Model):
#    def __init__(self, get_response):
#        self.get_response = get_response

#    def __call__(self, request):
#        if not request.session.session_key:
#            request.session.save()

#        response = self.get_response(request)
#        return response

class UserSession(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=40, default="")
    

class Extrasens(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True)
    
    @receiver(post_save, sender=User)
    def create_latest_inputs_1(sender, instance, created, **kwargs):
        if created:
            Extrasens.objects.create(user=instance)

    def __str__(self):
        return self.user
    
class NumUser(models.Model):
    session_key = models.CharField(max_length=40, default="")
    number = models.CharField(max_length=2, verbose_name='Введите загаданное число', null=True)

    def __str__(self):
        return self.number
    
class Extrasens_1(models.Model):
    session_key = models.CharField(max_length=40, default="")
    reliability = models.CharField(max_length=2, null=True)
    number = models.CharField(max_length=2, null=True)
        
    @staticmethod
    def randint():
        return randint(10, 99)
    
    def __str__(self):
        return self.number
    
class Extrasens_2(models.Model):
    session_key = models.CharField(max_length=40, default="")
    reliability = models.CharField(max_length=2, null=True)
    number = models.CharField(max_length=2, null=True)
        
    @staticmethod
    def randint():
        return randint(10, 99)
    
    def __str__(self):
        return self.number

extrasens/extratest/forms.py
from django import forms

class UserForm(forms.Form):
    num_user = forms.CharField(max_length=100, label="Введите загаданное число")

extrasens/extratest/views.py
from django.shortcuts import render
from .models import NumUser, Extrasens_1, Extrasens_2, UserSession
from django.http import HttpResponse
from django.contrib.auth.signals import user_logged_in


#def user_logged_in_handler(sender, request, user, **kwargs):
#    UserSession.objects.get_or_create(user = user, session_id = request.session.session_key)

#user_logged_in.connect(user_logged_in_handler)

#def delete_user_sessions(user):
#    user_sessions = UserSession.objects.filter(user = user)
#    for user_session in user_sessions:
#        user_session.session.delete()

def index(request):
    template = 'extratest/index.html'
    title = 'Главная страница'
    context = {
            'title': title,
    }
    return render(request, template, context)

def examples(request):
    template = 'extratest/examples.html'
    title = 'Варианты экстрасенсов'
    num_extrasens_1 = Extrasens_1()
    request.session['username'] = 'mike'
    num_extrasens_1.number = Extrasens_1.randint()
    num_extrasens_1.save()
    num_extrasens_2 = Extrasens_2()
    num_extrasens_2.number = Extrasens_2.randint()
    num_extrasens_2.save()
    context = {
        'num_extrasens_1': num_extrasens_1,
        'num_extrasens_2': num_extrasens_2,
        'title': title,
    }
    return render(request, template, context) 

def input_number(request):
    template = 'extratest/input_number.html'
    title = 'Страница ввода числа'
    
    if request.method == 'POST':
        num_user = NumUser()
        num_user.number = request.POST.get("num_user")
        num_user.save()
        context = {
            'num_user': num_user,
            'title': title,
        }
        return render(request, template, context)
        
    else:
        num_user = NumUser()
        context = {
            'num_user': num_user,
            'title': title,
        }
        return render(request, template, context)

def results(request):
    template = 'extratest/results.html'
    title = 'Результаты тестирования'
    list_num_extrasens_1 = Extrasens_1.objects.all()
    list_num_extrasens_2 = Extrasens_2.objects.all()
    list_num_user = NumUser.objects.all()
    rel_extrasens_1 = 0
    rel_extrasens_2 = 0
    for i in range(len(list_num_extrasens_1)):
        if list_num_extrasens_1[i].number == list_num_user[i].number:
            rel_extrasens_1 += 1
        else:
            rel_extrasens_1 -= 1

    for i in range(len(list_num_extrasens_2)):
        if list_num_extrasens_2[i].number == list_num_user[i].number:
            rel_extrasens_2 += 1
        else:
            rel_extrasens_2 -= 1
   
    context = {
        'list_num_extrasens_1': list_num_extrasens_1,
        'list_num_extrasens_2': list_num_extrasens_2,
        'list_num_user': list_num_user,
        'rel_extrasens_1': rel_extrasens_1,
        'rel_extrasens_2': rel_extrasens_2,
        'title': title,
    }
    return render(request, template, context)

extrasens/templates/extratest/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Тестирование экстрасенсов</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
        <a href="{% url 'extratest:index' %}">
          Главная страница</a>
        <a href="{% url 'extratest:examples' %}">
          Варианты экстрасенсов</a>
        <a href="{% url 'extratest:input_number' %}">
          Страница ввода числа</a>
        <a href="{% url 'extratest:results' %}">
          Результаты тестирования</a>
      </nav>
      <div class="container py-5">
      <h1>{% block title %}{% endblock %}</h1>
      </div>
    </header>
    <main>
      <div class="container py-5">
      {% block content %}
      {% endblock %}
      </div>
    </main>
    <footer>
    <div class="container py-5">
      По заказу компании "Эдисон"
    </div>
    </footer>
  </body>
</html> 

extrasens/templates/extratest/examples.html
{% extends 'extratest/base.html' %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
  <h3>Ниже представлены варианты экстрасенсов:</h3>
  <p>Вариант экстрасенса №1<br>
  {{ num_extrasens_1.number }}<br><br>
  Вариант экстрасенса №2<br>
  {{ num_extrasens_2.number }}<br><br></p>
<div>
  <p>Если готовы, то переходите на
    <a href="{% url 'extratest:input_number' %}">
      Страницу ввода числа</a></p>
</div>
{% endblock %}

extrasens/templates/extratest/index.html
{% extends 'extratest/base.html' %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
<p>Добро пожаловать! Загадайте двузначное число и нажмите
  <a href="{% url 'extratest:examples' %}">
    Подтверждаю!</a> когда будете готовы.</p>
{% endblock %}

extrasens/templates/extratest/input_number.html
{% extends 'extratest/base.html' %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
  <form method="post" action="">
    {% csrf_token %}
    <label>Введите загаданное число</label><br>
    <input type="text" name="num_user"/>
    <input type="submit" value="Отправить"/>
  </form>
  <br>
  <div>
    <p>Вы можете перейти к 
      <a href="{% url 'extratest:results' %}">
        Результатам тестирования</a></p>
  </div>
  <br>
  <div>
    <p>Если хотите попробовать ещё раз, то переходите на
      <a href="{% url 'extratest:index' %}">
        Главную страницу</a></p>
  </div>
{% endblock %}

extrasens/templates/extratest/results.html
{% extends 'extratest/base.html' %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-sm">
      История догадок первого экстрасенса:<br>
      {% if list_num_extrasens_1.count > 0 %}
      {% for num_extrasens_1 in list_num_extrasens_1 %}
      {{ num_extrasens_1.number }}<br>
      {% endfor %}
      {% endif %}
    </div>
    <div class="col-sm">
      История догадок второго экстрасенса:<br>
      {% if list_num_extrasens_2.count > 0 %}
      {% for num_extrasens_2 in list_num_extrasens_2 %}
      {{ num_extrasens_2.number }}<br>
      {% endfor %}
      {% endif %}
    </div>
    <div class="col-sm">
      История введённых пользователем чисел:<br>
      {% if list_num_user.count > 0 %}
      {% for num_user in list_num_user %}
      {{ num_user.number }}<br>
      {% endfor %}
      {% endif %}
    </div>
    <div class="col-sm">
      Достоверность первого экстрасенса:<br>
      {{ rel_extrasens_1 }}
    </div>
    <div class="col-sm">
      Достоверность второго экстрасенса:<br>
      {{ rel_extrasens_2 }}<br>
      {{ request.session }}
    </div>
  </div>
  <br>
  <div>
    <p>Если хотите попробовать ещё раз, то переходите на
      <a href="{% url 'extratest:index' %}">
        Главную страницу</a></p>
  </div>
{% endblock %}